name: Cleanup GHCR images

on:
  schedule:
    - cron: "0 3 * * 0" # Runs every Sunday at 3:00 AM
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: jenkins-docker-builder
          package-type: container
          delete-only-untagged-versions: true